### ISSUE TITLE
logging out and then closing logout window causes nullptrexception in server

### ISSUE THREAD

**Issue by dolenle** [halcyon94/Set#5]

**Comment by sheryanresutov** [comment]
i could fix this on the backend, but it wouldn't be proper. The errors occuring in Client.windowClosing(), where it tries to logout a player a 2nd time after the player has already logged out, and thus it tries to recover a hashmap entry that has been removed

**Comment by dolenle** [comment]
so i shouldn’t do connection.logout when closing the jframe? or do i need to check specifically to avoid doing that when not logged in?

**Comment by sheryanresutov** [comment]
map out all the times u logout/leavegame and in the windowClosing funct just do case work

**Comment by dolenle** [comment]
fixed in 0dc240b0d8
